Update code to Cakephp 3.6
narendravaghela/cakephp-mailgun pull request #14
Opened 2018-07-03 23:13 UTC by alysson-azevedo

This pull-requests makes this plugin to be compatible with cakephp 3.6.

On composer.json, i added two extensions, "ext-mbstring" and "ext-json", (both are already required on cakephp) so the phpcs don't complain about the methods like json_encode() not being on the composer.
I also updated the phpunit version because cakephp 3.6 requires it.
The mailgun-php version is set on 2.1.* because of #13

Everything else is just the substitution of deprecated methods to its proper getters and setters.

2018-07-04 05:17 UTC, narendravaghela requested changes

2018-07-04 05:17 UTC, narendravaghela commented on composer.json
> +        "cakephp/cakephp": ">=3.6.0",
I think ^3.4.0 would be sufficient.

2018-07-04 05:17 UTC, narendravaghela commented on composer.json
>          "php": ">=5.5.9",
Let's make it >=5.6.0

2018-07-04 05:48 UTC, narendravaghela commented
Also, the build is failed - https://travis-ci.org/narendravaghela/cakephp-mailgun/builds/399803780

`composer install --prefer-dist` fails due to version compatibility.

2018-07-04 06:04 UTC, narendravaghela commented
One more thought - implement the native Mailgun API [https://documentation.mailgun.com/en/latest/api-sending.html#sending] instead of using their library.

2018-07-04 11:58 UTC, alysson-azevedo commented on composer.json
> +        "cakephp/cakephp": ">=3.6.0",
You are right.

2018-07-04 11:58 UTC, alysson-azevedo commented on composer.json
>          "php": ">=5.5.9",
Agree.

2018-07-04 12:25 UTC, alysson-azevedo commented
I'll check these travis errors latter today.

2018-07-31 01:17 UTC, alysson-azevedo commented
Hi, i've been very busy, but new few days i'll be able to finish this pull-request.

2018-07-31 21:28 UTC, alysson-azevedo commented
The problem was this [silly error](https://github.com/sebastianbergmann/phpunit-mock-objects/pull/370#issuecomment-317999031) of mine.

2018-07-31 21:55 UTC, alysson-azevedo commented
Well, now i didn't understand that error. Here i run:
```
$ php -v
PHP 5.6.37-1+ubuntu18.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

$ composer --version
Composer 1.6.3 2018-01-31 16:28:17

$ ./vendor/phpunit/phpunit/phpunit --stderr
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

......                                                              6 / 6 (100%)

Time: 74 ms, Memory: 8.50MB

OK (6 tests, 10 assertions)

```

Do you know what it could be?

2018-08-01 14:12 UTC, narendravaghela commented
You mean it is working on your local environment, and not on Travis? Need to check...

2018-08-01 17:18 UTC, alysson-azevedo commented
Yes, it's the sabe php version, cakephp version and phpunit version.

And the error is really strange. I'll try again later today

2018-08-01 23:07 UTC, alysson-azevedo commented
Well, i've no idea. Found nothing on internet.
It doesn't look like it is related to [cakephp issue 10814](https://github.com/cakephp/cakephp/issues/10814).

And to be honest, it's been very hard to find time between work, colege and family, so if you think this pull request is still not ok, let's close it.

2018-08-03 04:55 UTC, narendravaghela commented
Hi @alysson-azevedo 
Thanks for your efforts. I will try to look into this in the weekend.

2018-08-08 13:09 UTC, alysson-azevedo commented
> One more thought - implement the native Mailgun API [https://documentation.mailgun.com/en/latest/api-sending.html#sending] instead of using their library.

It's a good idea, but it's better to wait the new Cake Mailer:
https://github.com/cakephp/cakephp/issues/12114

2018-08-12 22:13 UTC, burzum commented
@alysson-azevedo the new mailer won't happen any time soon if you follow the conversation of the ticket. If the change is going to happen then it is in 5.x.

2018-10-05 07:54 UTC, dakota commented
Any chance of merging this?

2018-10-05 09:40 UTC, narendravaghela commented
Hi @dakota 
I am going to rewrite this with Mailgun APIs. Most probably you can expect this by this weekend :)

2018-10-05 14:06 UTC, alysson-azevedo commented
I think it would be great to release this merge as a minor update and then rewrite the API and release it as a major update.

People probably extended this plugin so any changes could possibly break.

2018-10-05 14:20 UTC, merged

2018-10-05 14:28 UTC, narendravaghela commented
Thanks @alysson-azevedo 
I just merged the PR.
And regarding rewrite, yes that will be some breaking changes.